apiVersion: v1
kind: ReplicationController
metadata:
  name: jsapp
spec:
  replicas: 3
  selector:
    app: jsapp
  template:
    metadata:
      name: jsapp
      labels:
        app: jsapp
    spec:
      containers:
      - name: jsapp
        image: lubowsky/k8-s-docker
        ports:
        - containerPort: 8080
